quarkus:
  flyway:
    migrate-at-start: true
  jooq:
    dialect: MySql
  datasource:
    db-kind: mariadb
    username: root
    password: root
    jdbc:
      url: jdbc:mariadb://localhost:3306/gdsc-library